GET http://localhost:8080/api/v1/contacts/search-contact?email=sam@mail.com&phoneNumber=8858473879
Accept: application/json

###
DELETE http://localhost:8080/api/v1/contacts/delete-contact/1
Accept: application/json

###

PATCH http://localhost:8080/api/v1/contacts/update-contact/1
Content-Type: application/json

{
  "firstName": "Name changed",
  "address": "Also changed"
}

###

GET http://localhost:8080/api/v1/contacts/contact-address/2
Accept: application/json

<> 2025-08-08T101007.200.json
<> 2025-08-08T100722.404.json
<> 2025-08-08T092729.500.json
<> 2025-08-08T092715.200.json
<> 2025-08-08T092651.200.json

###
POST http://localhost:8080/api/v1/contacts/create-contact
Content-Type: application/json

{
  "firstName": "Sam",
  "lastName" : "Barth",
  "otherName": "Howels",
  "email": "sam@mail.com",
  "phoneNumber": "0807644322",
  "address": "Abuja"
}

<> 2025-08-08T074635.201.json
<> 2025-08-08T072821.200.json
<> 2025-08-08T072717.200.json
<> 2025-08-08T072404.404.json
<> 2025-08-08T072314.404.json

###
GET http://localhost:8080/api/v1/contacts/all-contacts
Accept: application/json

<> 2025-08-08T074706.200.json

###